#!/usr/bin/env python3
"""Set up TrustPager API access for Claude Code skills (first-run wizard).

When to use:
- Right after cloning this repo. This is the first thing a customer runs.
- After regenerating your TrustPager API key.
- After running config.py --clear to wipe an old key.

What it does:
- Looks for an existing tp_live_* key in Claude Code's MCP config
  (~/.claude/.mcp.json or ~/.claude/settings.json or ~/.claude.json).
- If found, offers to reuse it (no copy-paste needed).
- Otherwise, prompts you to paste your tp_live_... key.
- Writes the key (and this clone's location, bos_home) to ~/.claude/bos.json.
- Writes a tiny launcher shim to ~/.claude/bos-run.py so skills can run their
  data-fetchers from any working directory (`python ~/.claude/bos-run.py <skill>`).

Usage:
    python tools/setup.py
    python tools/setup.py --force        # overwrite an existing key

Next step after this runs: python tools/check-install.py
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from trustpager_api import CONFIG_PATH  # noqa: E402


def _repo_root() -> Path:
    """This clone's root (the dir that contains tools/ and requirements.txt)."""
    return Path(__file__).resolve().parent.parent


# The always-needed keyless document stack. Bundled here so a normal install has
# the floor with ZERO manual steps (D11: the BOS does setup, never hands the
# owner a command). These mirror requirements.txt; check-install.py --fix heals
# them later if anything is missing. Installed with the SAME interpreter
# (sys.executable -m pip) so there's no Windows multi-Python mismatch.
_DOC_STACK = [
    "markitdown[docx,pdf,xlsx,pptx]",
    "python-docx",
    "openpyxl",
    "reportlab",
    "pdfplumber",
]


def _install_doc_stack() -> int:
    """Install the bundled keyless document stack via this interpreter's pip.

    Best-effort: a failure here does not abort setup (the key step still runs,
    and check-install.py --fix can heal the doc stack later), but it is reported.
    Returns the pip return code (0 == success).
    """
    req = _repo_root() / "requirements.txt"
    if req.is_file():
        cmd = [sys.executable, "-m", "pip", "install", "-r", str(req)]
    else:
        cmd = [sys.executable, "-m", "pip", "install", *_DOC_STACK]
    print("Setting up the document tools (read/write Word, Excel, PDF). This is")
    print("a one-time install so you never have to touch a command yourself:")
    print(f"  {' '.join(cmd)}")
    try:
        rc = subprocess.run(cmd).returncode
    except OSError as e:
        print(f"  [warn] couldn't run pip ({e}). "
              "You can heal this later with: python tools/check-install.py --fix")
        return 1
    if rc == 0:
        print("  Document tools ready.")
    else:
        print("  [warn] document tools didn't fully install. "
              "Heal it later with: python tools/check-install.py --fix")
    print()
    return rc


def _walk_for_key(obj: Any) -> str | None:
    if isinstance(obj, str):
        if obj.startswith("tp_live_") and len(obj) > 20:
            return obj
        return None
    if isinstance(obj, dict):
        for v in obj.values():
            r = _walk_for_key(v)
            if r:
                return r
    if isinstance(obj, list):
        for v in obj:
            r = _walk_for_key(v)
            if r:
                return r
    return None


def _find_key_in_mcp_config() -> str | None:
    """Look for an existing TrustPager API key in Claude Code's MCP config."""
    candidates = [
        Path.home() / ".claude" / ".mcp.json",
        Path.home() / ".claude" / "settings.json",
        Path.home() / ".claude.json",
    ]
    for path in candidates:
        if not path.exists():
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        found = _walk_for_key(data)
        if found:
            return found
    return None


# The fixed-location shim. It lives at ~/.claude/bos-run.py — the one path that
# is known regardless of working directory or how BOS was installed. It reads
# bos_home from bos.json (same dir) and hands off to <bos_home>/tools/run.py,
# which carries the real logic and is versioned in the repo. Keep this DUMB so
# it rarely needs regenerating.
_SHIM_SOURCE = '''#!/usr/bin/env python3
# Auto-generated by Business Operating System setup.py. Do not edit by hand.
# Bootstraps the CWD-independent skill launcher from any working directory.
# Re-run `python tools/setup.py` to regenerate.
import json, subprocess, sys
from pathlib import Path

_cfg = Path.home() / ".claude" / "bos.json"
try:
    _home = json.loads(_cfg.read_text(encoding="utf-8")).get("bos_home")
except (OSError, ValueError):
    _home = None
if not _home:
    sys.stderr.write("[err] bos_home not set. Run: python tools/setup.py\\n")
    sys.exit(2)
_run = Path(_home) / "tools" / "run.py"
if not _run.is_file():
    sys.stderr.write(f"[err] launcher missing at {_run}. Re-run python tools/setup.py\\n")
    sys.exit(2)
# subprocess (not os.execv): execv on Windows splits argv entries containing
# spaces, which breaks install paths like "...\\Final Piece\\...".
sys.exit(subprocess.run([sys.executable, str(_run), *sys.argv[1:]]).returncode)
'''


def _bos_home() -> str:
    """Absolute path to this clone's root (the dir that contains tools/)."""
    return str(Path(__file__).resolve().parent.parent)


def _write_launcher_shim() -> Path:
    shim = CONFIG_PATH.parent / "bos-run.py"
    shim.write_text(_SHIM_SOURCE, encoding="utf-8")
    return shim


def _write_key(key: str) -> int:
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Preserve any existing config keys; just update api_key + bos_home.
    cfg: dict[str, Any] = {}
    if CONFIG_PATH.exists():
        try:
            cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8")) or {}
        except (json.JSONDecodeError, OSError):
            cfg = {}
    cfg["api_key"] = key
    cfg["bos_home"] = _bos_home()
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    print(f"Wrote {CONFIG_PATH}")
    shim = _write_launcher_shim()
    print(f"Wrote {shim}  (skills run via: python ~/.claude/bos-run.py <skill>)")
    print()
    print("Next: run `python tools/check-install.py` to verify everything works.")
    return 0


def _write_keyless() -> int:
    """Finish setup without a TrustPager key.

    Writes bos_home into bos.json and deploys the launcher shim so the
    keyless document floor is fully operational.  No api_key is written.
    """
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    cfg: dict[str, Any] = {}
    if CONFIG_PATH.exists():
        try:
            cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8")) or {}
        except (json.JSONDecodeError, OSError):
            cfg = {}
    cfg["bos_home"] = _bos_home()
    # Do not set or clear api_key; preserve any existing value.
    CONFIG_PATH.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    shim = _write_launcher_shim()
    print(f"Wrote {shim}  (skills run via: python ~/.claude/bos-run.py <skill>)")
    print()
    print("No key set. The keyless floor is ready to use. "
          "You can connect TrustPager later to unlock the connected features.")
    print()
    print("Next: run `python tools/check-install.py` to verify everything works.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing key without prompting")
    parser.add_argument("--skip-deps", action="store_true",
                        help="Skip installing the bundled document stack")
    args = parser.parse_args()

    print("Business Operating System: first-run setup")
    print()

    # Bundle the always-needed keyless document stack first (D11). This makes the
    # keyless document floor work with zero manual steps. It is independent of any
    # TrustPager key, so a keyless owner gets it too.
    if not args.skip_deps:
        _install_doc_stack()

    print(f"This will write your TrustPager API key to: {CONFIG_PATH}")
    print("(optional: the keyless floor works without it)")
    print()

    existing_key = None
    if CONFIG_PATH.exists() and not args.force:
        try:
            cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
            existing_key = (cfg.get("api_key") or "").strip()
        except (json.JSONDecodeError, OSError):
            pass
        if existing_key:
            print(f"A key is already configured (ends ...{existing_key[-4:]}).")
            # Idempotent backfill for upgraders: ensure bos_home + the launcher
            # shim exist even when we're not touching the key.
            if cfg.get("bos_home") != _bos_home():
                cfg["bos_home"] = _bos_home()
                CONFIG_PATH.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
                print(f"Updated bos_home in {CONFIG_PATH}")
            shim = _write_launcher_shim()
            print(f"Ensured launcher shim at {shim}")
            print("Re-run with --force to replace the key, or skip setup entirely.")
            return 0

    detected = _find_key_in_mcp_config()
    if detected:
        print(f"Detected an existing TrustPager API key in Claude Code config")
        print(f"  (ends ...{detected[-4:]}).")
        choice = input("Use this key for skill scripts too? [Y/n] ").strip().lower()
        if choice in ("", "y", "yes"):
            return _write_key(detected)

    print("Get your key from: https://app.trustpager.com/settings/api")
    print()
    key = input("Paste your tp_live_... key (or press Enter to skip): ").strip()
    if not key:
        return _write_keyless()
    if not key.startswith("tp_live_"):
        print(f"WARNING: key doesn't start with 'tp_live_'. Got '{key[:10]}...'",
              file=sys.stderr)
        confirm = input("Use it anyway? [y/N] ").strip().lower()
        if confirm not in ("y", "yes"):
            return 2
    return _write_key(key)


if __name__ == "__main__":
    sys.exit(main())
